server:
  port: 8003
eureka:
  instance:
    hostname: eureka3.kk.com
  client:
    # 是否作为客户端主动对外注册
    register-with-eureka: true
    # 是否从别的Server拉取客户端注册信息
    fetch-registry: true
    # 此处serviceUrl必须使用驼峰法！使用service-url的话，检测不到，会继续使用默认的地址。
    serviceUrl:
      defaultZone: http://eureka2.kk.com:8002/eureka/,http://eureka1.kk.com:8001/eureka/