spring:
  application:
    name: eureka-provider-bye
server:
  port: 9002
eureka:
  client:
    # 是否作为客户端主动对外注册
    register-with-eureka: true
    # 是否从别的Server拉取客户端注册信息
    fetch-registry: false
    serviceUrl:
      # Eureka server的地址, 只会注册到eureka集群的节点1上，如果集群启动，会自动同步注册信息到其他节点上.
      defaultZone: http://eureka0.kk.com:8000/eureka/
  instance:
    # 使用不同的主机地址，和hello区分为【不同的两个】服务
    hostname: provider2.kk.com
    lease-renewal-interval-in-seconds: 3